### ISSUE TITLE
Calculating nDTW

### ISSUE THREAD

**Issue by raphael-sch** [VegB/VLN-Transformer#3]
I have a question about calculating nDTW that is unclear to me:

Shouldn't "_SUCCESS_THRESHOLD" be set to 1. The binary success is determined if the agent stops within 1 panorama from the target panorama.

**Comment by VegB** [comment]
Hi, thanks for your question.
In the [Touchdown ](https://arxiv.org/pdf/1811.12354.pdf)task setup, it mentions that

> We consider an execution correct if the agent reaches the exact goal position or one of its neighboring nodes in the environment graph.

Another implementation (VALAN) on Touchdown task can be found [here](https://github.com/google-research/valan/blob/9fc6e38f411e6cb76408bf033cdc056ace980973/touchdown/td_problem.py#L44).

**Comment by raphael-sch** [comment]
Thanks
